// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPbAN408Ocfp5sZKdS339YTBh3q5jIWG8',
    appId: '1:312901671682:web:174e4a39e99d3dec16001b',
    messagingSenderId: '312901671682',
    projectId: 'trainingmachine-1c76c',
    authDomain: 'trainingmachine-1c76c.firebaseapp.com',
    storageBucket: 'trainingmachine-1c76c.appspot.com',
    measurementId: 'G-5SHMHF3B7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlgzk-jyM4abY-6-gp3xWFsch5fXMyyr0',
    appId: '1:312901671682:android:e194b91aa3d0483e16001b',
    messagingSenderId: '312901671682',
    projectId: 'trainingmachine-1c76c',
    storageBucket: 'trainingmachine-1c76c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABVY1_Sy78pXB8q3dBs3_4ErvpEUVB-iU',
    appId: '1:312901671682:ios:98616b4f9f89d30416001b',
    messagingSenderId: '312901671682',
    projectId: 'trainingmachine-1c76c',
    storageBucket: 'trainingmachine-1c76c.appspot.com',
    iosBundleId: 'com.example.training',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABVY1_Sy78pXB8q3dBs3_4ErvpEUVB-iU',
    appId: '1:312901671682:ios:2ecd7c60d0721f8b16001b',
    messagingSenderId: '312901671682',
    projectId: 'trainingmachine-1c76c',
    storageBucket: 'trainingmachine-1c76c.appspot.com',
    iosBundleId: 'com.example.training.RunnerTests',
  );
}
